# Generated by Django 4.2 on 2023-04-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='desctiption',
            new_name='description',
        ),
    ]
